# Form implementation generated from reading ui file 'c:\Users\Estudante\Desktop\Projetos Python\curso-python-2022\boas_vindas_gui\janela.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(339, 148)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Estudante\\Desktop\\Projetos Python\\curso-python-2022\\boas_vindas_gui\\icone.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Janela.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_nome = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome.setGeometry(QtCore.QRect(20, 10, 49, 16))
        self.lbl_nome.setObjectName("lbl_nome")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(110, 40, 72, 24))
        self.btn_sair.setObjectName("btn_sair")
        self.btn_entrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entrar.setGeometry(QtCore.QRect(187, 40, 72, 24))
        self.btn_entrar.setObjectName("btn_entrar")
        self.lbl_resultado = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultado.setGeometry(QtCore.QRect(10, 80, 301, 16))
        self.lbl_resultado.setObjectName("lbl_resultado")
        self.txt_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nome.setGeometry(QtCore.QRect(60, 10, 201, 22))
        self.txt_nome.setObjectName("txt_nome")
        Janela.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Janela)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 339, 22))
        self.menubar.setObjectName("menubar")
        Janela.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Janela)
        self.statusbar.setObjectName("statusbar")
        Janela.setStatusBar(self.statusbar)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Boas-vindas"))
        self.lbl_nome.setText(_translate("Janela", "Nome:"))
        self.btn_sair.setText(_translate("Janela", "Sair"))
        self.btn_entrar.setText(_translate("Janela", "Entrar"))
        self.lbl_resultado.setText(_translate("Janela", "Resultado: "))
