# Form implementation generated from reading ui file 'c:\Users\Estudante\Desktop\Projetos Python\curso-python-2022\modulo-2\calculadora_gui\output\tela.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(190, 10, 211, 41))
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_num1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num1.setGeometry(QtCore.QRect(30, 80, 91, 31))
        self.lbl_num1.setObjectName("lbl_num1")
        self.btn_som = QtWidgets.QPushButton(self.centralwidget)
        self.btn_som.setGeometry(QtCore.QRect(320, 120, 51, 24))
        self.btn_som.setObjectName("btn_som")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(320, 160, 51, 24))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(320, 200, 51, 24))
        self.btn_mult.setObjectName("btn_mult")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(320, 240, 51, 24))
        self.btn_div.setObjectName("btn_div")
        self.lbl_oper = QtWidgets.QLabel(self.centralwidget)
        self.lbl_oper.setGeometry(QtCore.QRect(300, 80, 91, 31))
        self.lbl_oper.setObjectName("lbl_oper")
        self.lbl_num2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num2.setGeometry(QtCore.QRect(170, 80, 91, 31))
        self.lbl_num2.setObjectName("lbl_num2")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(440, 80, 91, 31))
        self.lbl_result.setObjectName("lbl_result")
        self.txt_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(20, 180, 113, 22))
        self.txt_num1.setObjectName("txt_num1")
        self.txt_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(160, 180, 113, 22))
        self.txt_num2.setObjectName("txt_num2")
        self.lbl_saida = QtWidgets.QLabel(self.centralwidget)
        self.lbl_saida.setGeometry(QtCore.QRect(440, 170, 91, 51))
        self.lbl_saida.setObjectName("lbl_saida")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.lbl_titulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700; color:#00007f;\">CALCULADORA</span></p></body></html>"))
        self.lbl_num1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">Núm 01</span></p></body></html>"))
        self.btn_som.setText(_translate("MainWindow", "+"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.lbl_oper.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">Operação</span></p></body></html>"))
        self.lbl_num2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">Núm 02</span></p></body></html>"))
        self.lbl_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">Resultado</span></p></body></html>"))
        self.lbl_saida.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
