# Form implementation generated from reading ui file 'c:\Users\Estudante\Desktop\Projetos Python\curso-python-2022\modulo-2\projetos_gui\tela.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tb_dados = QtWidgets.QTableView(self.centralwidget)
        self.tb_dados.setGeometry(QtCore.QRect(30, 60, 901, 311))
        self.tb_dados.setObjectName("tb_dados")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 20, 111, 31))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(620, 380, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbn_load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.tbn_load.setObjectName("tbn_load")
        self.horizontalLayout.addWidget(self.tbn_load)
        self.tbn_calc = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.tbn_calc.setObjectName("tbn_calc")
        self.horizontalLayout.addWidget(self.tbn_calc)
        self.tbn_salvar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.tbn_salvar.setObjectName("tbn_salvar")
        self.horizontalLayout.addWidget(self.tbn_salvar)
        self.lbl_resultado = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultado.setGeometry(QtCore.QRect(40, 420, 721, 31))
        self.lbl_resultado.setStyleSheet("font: 700 14pt \"Segoe UI\";")
        self.lbl_resultado.setObjectName("lbl_resultado")
        self.txt_resultado = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_resultado.setGeometry(QtCore.QRect(40, 450, 891, 131))
        self.txt_resultado.setStyleSheet("font: 700 14pt \"Segoe UI\";")
        self.txt_resultado.setReadOnly(True)
        self.txt_resultado.setObjectName("txt_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700;\">PROJETOS</span></p></body></html>"))
        self.tbn_load.setText(_translate("MainWindow", "Carregar"))
        self.tbn_calc.setText(_translate("MainWindow", "Calcular"))
        self.tbn_salvar.setText(_translate("MainWindow", "Salvar"))
        self.lbl_resultado.setText(_translate("MainWindow", "Resultado: "))
